### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by filtrated** [Not-Cyrus/repl.it-scraper#2]
![image](https://user-images.githubusercontent.com/71861371/112773296-7492a000-9003-11eb-926d-94bc5bebee4e.png)

literally is giving me a error at first it was color module i fixed that error but idk how to fix this
any help?

**Comment by Not-Cyrus** [comment]
![LMFAO](https://user-images.githubusercontent.com/50967051/112773656-c7208c00-9004-11eb-93c4-7f78ad2625d3.png)
